# Generated by Django 5.1 on 2024-10-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_espera', 'En espera'), ('procesado', 'Procesado'), ('entregado', 'Entregado')], default='en_espera', max_length=20),
        ),
    ]
