# Generated by Django 5.1 on 2024-08-21 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0002_remove_producto_precio_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.TextField(default='en espera'),
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
