# Generated by Django 5.1 on 2024-11-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0001_initial'),
        ('pedidos', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='medio_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='medios_pago.mediopago', verbose_name='Medio de Pago'),
        ),
    ]
