# Generated by Django 5.1 on 2024-08-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_medida',
            field=models.CharField(default='unidad', max_length=10),
        ),
    ]
