# Generated by Django 5.1 on 2024-09-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_tipo_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('peso', 'Peso (kg)')], default='unidad', max_length=10),
        ),
    ]
