# Generated by Django 5.1 on 2024-10-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('cuit', models.CharField(max_length=35)),
                ('email', models.EmailField(blank=True, max_length=35, null=True)),
                ('direccion', models.CharField(blank=True, max_length=35, null=True)),
                ('telefono', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
