# Generated by Django 5.1 on 2024-08-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_ciudad_pais_alter_cliente_email_cliente_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cuit',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
