# Generated by Django 5.1 on 2024-08-31 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.pais'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.provincia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.IntegerField(default='-'),
        ),
    ]
