# Generated by Django 5.1 on 2024-09-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_pais_cliente_provincia_alter_cliente_cuit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='provincia',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
