# Generated by Django 5.1 on 2024-09-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_cliente_ciudad_remove_provincia_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(max_length=35),
        ),
    ]
